// languageContent.js


export const englishContent = {
  heroTitle: "OUR STORY",
  heroSubtitle:
    "Learn a New Language, Discover New Opportunities",
  readMore: "READ MORE",
  featureTitle: "Feature",
  featureSubtitle: "Discover Our Courses",
  visitServicePage: "Visit Courses Page",
  aboutUsTitle: "ABOUT US",
  aboutUsSubtitle:
    "Learn a New Language, Discover New Opportunities",
  aboutUsDescription:
    "St. Anthony education center is a private company located in Africa,East Africa Rwanda, Kigali City, Remera sector,Giporoso it's where  Headquater are located. The company is legally allowed to carry  services all over the country. We train different courses online and at school. We offer both short-term and long-term trainings namely; vocational studies, languages, Aviation language and safety, Traffic rules and driving, Computer literacy, Recreational and sports trainings among others. We started training on 17thJuly, 2018. We receive local and international students and mainly study in their home countries through online platform.",
  financeTitle: "FINANCE",
  financeSubtitle: "SECURE YOUR FUTURE TODAY",
  professionalTraining: "Professional Training (CyberPro Academy)",
  professionalCourse: "Professional Course",
  professionalCertification: "Professional Certification",
  freeResource: "Free Resource",
  seminarsConferences: "Seminars/Conferences",
  enrollNow: "ENROLL NOW",
  consultingServices: "CONSULTING SERVICES",
  cyberSecurityAssessments: "Cyber Security Assessments",
  itSecurityAudit: "IT Security Audit",
  threatIntelligence: "Threat Intelligence",
  thirdPartyRiskAssessment: "Third-Party Risk Assessment",
  getExpertAdvice: "GET EXPERT ADVICE",
  cctvCameraSecurity: "CCTV CAMERA SECURITY SOLUTIONS",
  consultationAndAssessment: "Consultation And Assessment",
  professionalInstallation: "Professional Installation",
  upgradeAndExplanation: "Upgrade And Explanation",
  systemConfiguration: "System Configuration",
  maintenanceAndSupport: "Maintenance And Support",
  trainingInternship: "Training & Internship",
  fAll: "VIEW ALL",
  testimonialTitle: "TESTIMONIAL",
  customerReviews: "CUSTOMER REVIEWS",
  rateUs: "Rate us",
  rateUsSubtitle: "FROM 1 TO 5",
  choose: "CHOOSE",
  ourStaffTitle: "OUR STAFF",
  ourStaffSubtitle: "MEET OUR TEAM",
  contactTitle: "Contact",
  letsStart: "LETS START",
  secureYourFuture: "SECURE YOUR FUTURE TODAY",
  contactUs: "CONTACT US",
  followUs: "FOLLOW US",
  whatsNew: "WHAT'S NEW?",
  latestBlog: "OUR LATEST FROM BLOG",
  viewMore: "VIEW MORE",
  promise: "Secure your premises",
};

export const frenchContent = {
  heroTitle: "NOTRE HISTOIRE",
  heroSubtitle:
    "Apprenez une nouvelle langue, découvrez de nouvelles opportunités.",
  readMore: "LIRE LA SUITE",
  featureTitle: "Fonctionnalité",
  featureSubtitle: "Découvrez nos formations",
  visitServicePage: "Visiter la page des formations",
  aboutUsTitle: "À PROPOS DE NOUS",
  aboutUsSubtitle:
    "Apprenez une nouvelle langue, découvrez de nouvelles opportunités.",
  aboutUsDescription:
    "Le centre d'éducation St. Anthony est une entreprise privée située en Afrique, en Afrique de l'Est, au Rwanda, dans la ville de Kigali, dans le secteur de Remera, à Giporoso, c'est là que se trouve le siège social. L'entreprise est légalement autorisée à fournir des services dans tout le pays. Nous dispensons différents cours en ligne et à l'école. Nous proposons des formations à court et à long terme, à savoir : études professionnelles, langues, langage et sécurité de l'aviation, règles de circulation et conduite, alphabétisation informatique, formations récréatives et sportives, entre autres. Nous avons commencé la formation le 17 juillet 2018. Nous recevons des étudiants locaux et internationaux et étudions principalement dans leur pays d'origine via une plateforme en ligne.",
  financeTitle: "FINANCE",
  financeSubtitle: "SÉCURISEZ VOTRE AVENIR AUJOURD'HUI",
  professionalTraining: "Formation professionnelle (CyberPro Academy)",
  professionalCourse: "Cours professionnel",
  professionalCertification: "Certification professionnelle",
  freeResource: "Ressource gratuite",
  seminarsConferences: "Séminaires/Conférences",
  enrollNow: "S'INSCRIRE MAINTENANT",
  consultingServices: "SERVICES DE CONSEIL",
  cyberSecurityAssessments: "Évaluations de cybersécurité",
  itSecurityAudit: "Audit de sécurité informatique",
  threatIntelligence: "Renseignement sur les menaces",
  thirdPartyRiskAssessment: "Évaluation des risques tiers",
  getExpertAdvice: "OBTENIR DES CONSEILS D'EXPERTS",
  cctvCameraSecurity: "SOLUTIONS DE SÉCURITÉ CAMÉRA CCTV",
  consultationAndAssessment: "Consultation et évaluation",
  professionalInstallation: "Installation professionnelle",
  upgradeAndExplanation: "Mise à niveau et explication",
  systemConfiguration: "Configuration du système",
  maintenanceAndSupport: "Maintenance et support",
  trainingInternship: "Formation et stage",
  viewAll: "VOIR TOUT",
  testimonialTitle: "TÉMOIGNAGE",
  customerReviews: "AVIS DES CLIENTS",
  rateUs: "évaluez-nous",
  rateUsSubtitle: "DE 1 À 5",
  choose: "CHOISIR",
  ourStaffTitle: "NOTRE PERSONNEL",
  ourStaffSubtitle: "RENCONTREZ NOTRE ÉQUIPE",
  contactTitle: "Contact",
  letsStart: "COMMENÇONS",
  secureYourFuture: "SÉCURISEZ VOTRE AVENIR AUJOURD'HUI",
  contactUs: "NOUS CONTACTER",
  followUs: "SUIVEZ-NOUS",
  whatsNew: "QUOI DE NEUF ?",
  latestBlog: "NOTRE DERNIER BLOG",
  viewMore: "VOIR PLUS",
  promise: "Sécuriser vos locaux",
};

