// languageContent.js


export const englishContent = {
  heroTitle: "OUR STORY",
  heroSubtitle:
    "Secure Your Business, Your Career And Your Home By CyberPro Group",
  readMore: "READ MORE",
  featureTitle: "Feature",
  featureSubtitle: "Discover Our Services",
  visitServicePage: "Visit Service Page",
  aboutUsTitle: "ABOUT US",
  aboutUsSubtitle:
    "Secure Your Business, Your Career And Your Home By CyberPro Group",
  aboutUsDescription:
    "CyberPro Academy's mission is to mitigate cybersecurity risk through instruction in cybersecurity, computer security, information security, and operations. We do so by providing high-quality classroom instruction and training to students, managers, executives, and employees with a focus on filling critical job-related skill gaps. The company will begin with a small group of practitioners/instructors who are subject-matter experts in our core offerings.",
  financeTitle: "FINANCE",
  financeSubtitle: "SECURE YOUR FUTURE TODAY",
  professionalTraining: "Professional Training (CyberPro Academy)",
  professionalCourse: "Professional Course",
  professionalCertification: "Professional Certification",
  freeResource: "Free Resource",
  seminarsConferences: "Seminars/Conferences",
  enrollNow: "ENROLL NOW",
  consultingServices: "CONSULTING SERVICES",
  cyberSecurityAssessments: "Cyber Security Assessments",
  itSecurityAudit: "IT Security Audit",
  threatIntelligence: "Threat Intelligence",
  thirdPartyRiskAssessment: "Third-Party Risk Assessment",
  getExpertAdvice: "GET EXPERT ADVICE",
  cctvCameraSecurity: "CCTV CAMERA SECURITY SOLUTIONS",
  consultationAndAssessment: "Consultation And Assessment",
  professionalInstallation: "Professional Installation",
  upgradeAndExplanation: "Upgrade And Explanation",
  systemConfiguration: "System Configuration",
  maintenanceAndSupport: "Maintenance And Support",
  trainingInternship: "Training & Internship",
  fAll: "VIEW ALL",
  testimonialTitle: "TESTIMONIAL",
  customerReviews: "CUSTOMER REVIEWS",
  rateUs: "Rate us",
  rateUsSubtitle: "FROM 1 TO 5",
  choose: "CHOOSE",
  ourStaffTitle: "OUR STAFF",
  ourStaffSubtitle: "MEET OUR TEAM",
  contactTitle: "Contact",
  letsStart: "LETS START",
  secureYourFuture: "SECURE YOUR FUTURE TODAY",
  contactUs: "CONTACT US",
  followUs: "FOLLOW US",
  whatsNew: "WHAT'S NEW?",
  latestBlog: "OUR LATEST FROM BLOG",
  viewMore: "VIEW MORE",
  promise: "Secure your premises",
};

export const frenchContent = {
  heroTitle: "NOTRE HISTOIRE",
  heroSubtitle:
    "Sécurisez votre entreprise, votre carrière et votre maison avec CyberPro Group",
  readMore: "LIRE LA SUITE",
  featureTitle: "Fonctionnalité",
  featureSubtitle: "Découvrez nos services",
  visitServicePage: "Visiter la page des services",
  aboutUsTitle: "À PROPOS DE NOUS",
  aboutUsSubtitle:
    "Sécurisez votre entreprise, votre carrière et votre maison avec CyberPro Group",
  aboutUsDescription:
    "La mission de CyberPro Academy est d'atténuer les risques de cybersécurité grâce à l'enseignement de la cybersécurité, de la sécurité informatique, de la sécurité de l'information et des opérations. Nous le faisons en fournissant une instruction et une formation en classe de haute qualité aux étudiants, aux gestionnaires, aux cadres et aux employés, en mettant l'accent sur le comblement des lacunes critiques en matière de compétences liées à l'emploi. L'entreprise commencera avec un petit groupe de praticiens/instructeurs qui sont des experts en la matière dans nos offres principales.",
  financeTitle: "FINANCE",
  financeSubtitle: "SÉCURISEZ VOTRE AVENIR AUJOURD'HUI",
  professionalTraining: "Formation professionnelle (CyberPro Academy)",
  professionalCourse: "Cours professionnel",
  professionalCertification: "Certification professionnelle",
  freeResource: "Ressource gratuite",
  seminarsConferences: "Séminaires/Conférences",
  enrollNow: "S'INSCRIRE MAINTENANT",
  consultingServices: "SERVICES DE CONSEIL",
  cyberSecurityAssessments: "Évaluations de cybersécurité",
  itSecurityAudit: "Audit de sécurité informatique",
  threatIntelligence: "Renseignement sur les menaces",
  thirdPartyRiskAssessment: "Évaluation des risques tiers",
  getExpertAdvice: "OBTENIR DES CONSEILS D'EXPERTS",
  cctvCameraSecurity: "SOLUTIONS DE SÉCURITÉ CAMÉRA CCTV",
  consultationAndAssessment: "Consultation et évaluation",
  professionalInstallation: "Installation professionnelle",
  upgradeAndExplanation: "Mise à niveau et explication",
  systemConfiguration: "Configuration du système",
  maintenanceAndSupport: "Maintenance et support",
  trainingInternship: "Formation et stage",
  viewAll: "VOIR TOUT",
  testimonialTitle: "TÉMOIGNAGE",
  customerReviews: "AVIS DES CLIENTS",
  rateUs: "évaluez-nous",
  rateUsSubtitle: "DE 1 À 5",
  choose: "CHOISIR",
  ourStaffTitle: "NOTRE PERSONNEL",
  ourStaffSubtitle: "RENCONTREZ NOTRE ÉQUIPE",
  contactTitle: "Contact",
  letsStart: "COMMENÇONS",
  secureYourFuture: "SÉCURISEZ VOTRE AVENIR AUJOURD'HUI",
  contactUs: "NOUS CONTACTER",
  followUs: "SUIVEZ-NOUS",
  whatsNew: "QUOI DE NEUF ?",
  latestBlog: "NOTRE DERNIER BLOG",
  viewMore: "VOIR PLUS",
  promise: "Sécuriser vos locaux",
};

