import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";

import { Roboto, Merriweather } from "@next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ContextProvider from "@/components/HeaderAndFooter/contextProvider";
const roboto = Roboto({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

const merriweather = Merriweather({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-merriweather",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ContextProvider>
        <body
          className={`${roboto.variable} ${merriweather.variable} font-roboto`}
        >
          <Header />
          {children}
          <Footer />
        </body>
      </ContextProvider>
    </html>
  );
}
